[workspace]
members = ["core"]

[workspace.dependencies]
anyhow = "1"
pulldown-cmark = "0.9"
pulldown-cmark-to-cmark = "10"
syn = { version = "2", features = ["parsing", "full", "extra-traits"] }
quote = { version = "1" }
