[workspace]
members = ["core"]

[workspace.dependencies]
anyhow = "1"
pulldown-cmark = "0.9"
markdown = "1.0.0-alpha.7"
syn = { version = "2", features = ["parsing", "full", "extra-traits"] }
quote = { version = "1" }
